language: generic
sudo: required

services: 
  - docker

before_install:
  - docker build -t christian/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true christian/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-787624116074"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"