sudo: required
services: 
  - docker

before_install:
  - docker build -t christian christian/docker-react -f Dockerfile.dev Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test